### ISSUE TITLE
MultiInputForm++ ListView: Possible to exclude checkboxes from Highlight-in-view functionality

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#15]
Hi Mostafa,
I just noticed that the highlight-in-view behaviour also extends to the checkbox, so whenever I click on the checkbox of an element Revit will zoom to that element. I wonder if it is possible to limit highlight-in-view to the textlabel only.

**Comment by MostafaElAyoubi** [comment]
Hi Andreas,
thanks for pointing this out. I just fixed this in version 2017.05.06.
