### ISSUE TITLE
MultiInputForm++: Radio button labels trim text

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#16]
Hi Mostafa,
In some cases I have fairly long label texts for my radio buttons. Unfortunately they get trimmed by the form layout:
Input:
![radiobuttonslonglabeltexts](https://cloud.githubusercontent.com/assets/3014437/25857998/ee10bc10-34da-11e7-89ee-fd51c6a067d3.PNG)
Result:
![radiobuttonstrimmedlabels](https://cloud.githubusercontent.com/assets/3014437/25857873/9e001798-34da-11e7-8453-77bbc64fa65e.PNG)
Do you think there's a way of making the labels more flexible in terms of size?

**Comment by MostafaElAyoubi** [comment]
Hi Andreas,
I just added some code to adapt the height of radio button labels accordingly with the length of the text. 
I just updated the package (version 2017.5.9).
![image](https://cloud.githubusercontent.com/assets/20224923/25860793/f6657d1c-34e2-11e7-8354-b057b8e1543a.png)

**Comment by andydandy74** [comment]
Wow, that was fast. Thanks!
