### ISSUE TITLE
UI.SelectModelElementsData returns categories when no selection made

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#19]
Buttons of the ```uiselectelementsofcat``` class will return the categories of their category filter if no model element has been selected. It would be preferable if they returned null (single element selection) or an empty list (multi-element selection). 
One approach may be to check all button tags in ```setclose``` if they contain Revit categories and remove them.
![noselectionreturnscategories](https://cloud.githubusercontent.com/assets/3014437/25956317/b03be58a-366b-11e7-9e98-d229ef2929b2.PNG)

**Comment by MostafaElAyoubi** [comment]
That would indeed be a good approach since buttons should never return categories. I'll take care of it publish it in the next version along with all the great stuff you contributed.
