### ISSUE TITLE
UI.Boolean Input truncates label text

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#20]
@MostafaElAyoubi  - would be nice if this label could also scale based on text length
![booleanlabeltruncated](https://cloud.githubusercontent.com/assets/3014437/25998171/fc115080-371f-11e7-87be-ae76ad266c91.PNG)

**Comment by MostafaElAyoubi** [comment]
just fixed using same method as radio buttons: 
![image](https://cloud.githubusercontent.com/assets/20224923/25999386/371eea2a-3725-11e7-81ce-4dea4edda4e4.png)
this will be included in the next update of the package this week end!

**Comment by andydandy74** [comment]
Nice!
