### ISSUE TITLE
ListView: Sorting not locale-aware

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#23]
Hi @MostafaElAyoubi 
Just noticed that sorting will ignore "special" characters like a German "Umlaut" (ä,ö,ü):
![localeunaware](https://cloud.githubusercontent.com/assets/3014437/26499007/5647685c-4231-11e7-93b3-1f3d544288cb.PNG)
This looks fixable:
```For locale aware sorting, use locale.strxfrm() for a key function or locale.strcoll() for a comparison function.```
https://ironpython-test.readthedocs.io/en/latest/howto/sorting.html#odd-and-ends
Works fine in Dropdown node, by the way.

**Comment by MostafaElAyoubi** [comment]
Hi @andydandy74 , thanks for pointing this issue out and also providing the solution ! 👍  It seems to work well. I'll publish a new version of the package with this improvement this week end.

**Comment by MostafaElAyoubi** [comment]
I finally managed to solve this one! I found it rather hard to implement locale so I actually used unidecode data to create a defitnition that stript accents, and I used it as sorting key.Listviews in version 2017.06.03 of the package handle special characters and accents better now . 
```
def remove_accents(input_str):
      nfkd_form = unicodedata.normalize('NFKD', input_str)
      only_ascii = nfkd_form.encode('ASCII', 'ignore')
      return only_ascii	 
```

```
if j.sorted :
	lvItems = sorted(lvItems,key = remove_accents)
```

![image](https://user-images.githubusercontent.com/20224923/27004586-823bd782-4e0b-11e7-8e35-8f62444795c9.png)

**Comment by andydandy74** [comment]
👍
