### ISSUE TITLE
UI.DirectoryPath Data start at Default Path

### ISSUE THREAD

**Issue by cpalexander** [MostafaElAyoubi/Data-shapes#24]
Firstly, Data-Shapes is a great package and very useful.

A quick suggestion would be that in the UI.DirectoryPath Data module, when it is active in the UI, that if the user clicks the "button" to navigate to a location, that it does so starting at the default path set into the node. I think that that would be a great help.

**Comment by MostafaElAyoubi** [comment]
Hi @cpalexander that's a good suggestion. This functionaity has just been added. Try version 2017.06.03 of the package !

**Comment by david-pbk** [comment]
This doesn't seem to be working in the current release (Revit 22.0.10.28 - Dynamo 2.10.1.4002 - D/S 2022.2.96).  Tried a few different methods but I always get the default directory when I hit the button.

![image](https://user-images.githubusercontent.com/47759899/124959124-bf8f5c80-dfcf-11eb-9b36-494078aaf1b4.png)
