### ISSUE TITLE
Surface - RevitFaceReference

### ISSUE THREAD

**Issue by brunotux** [MostafaElAyoubi/Data-shapes#25]
When I use your Select Face node, I can not get the ref. element. With the standard dynamo node it works. I got the same problem with the "ui.selectfaces data" node.

![error](https://user-images.githubusercontent.com/7166455/27577733-0fe88300-5b22-11e7-841b-810c44b8db01.png)

Python Code:

```
import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
faces = IN[0]
elementlist = list()
for face in faces:
	try:
		ref = face.Tags.LookupTag("RevitFaceReference")
		elem = doc.GetElement(ref)
		elementlist.append(elem)
	except:
		elementlist.append(list())
OUT = elementlist
```

With the node from Dimitar Venkov it works also.

#Copyright(c) 2016, Dimitar Venkov
```
import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def output1(x):
	if len(x) == 1: return x[0]
	else : return x

surfaces, gpoints = [], []
sel1 = uidoc.Selection
ot1 = Selection.ObjectType.Face
ref_list = sel1.PickObjects(ot1, "Select the faces and press Finish.")
for ref in ref_list:
	el1 = doc.GetElement(ref.ElementId)
	sf0 = el1.GetGeometryObjectFromReference(ref)
	if isinstance(el1, FamilyInstance):
		**tf1 = el1.GetTransform().ToCoordinateSystem()
		sf1 = sf0.Convert(ref, tf1)**
	else:
		sf1 = sf0.ToProtoType(True)
	**for i in sf1: i.Tags.AddTag("RevitFaceReference", ref)**
	surfaces.append(output1(sf1) )
	gpoints.append(ref.GlobalPoint.ToPoint(True) )

OUT = output1(surfaces), output1(gpoints)
```

**Comment by MostafaElAyoubi** [comment]
Hi @brunotux  . Thanks a lot for reporting this and providing valuable info. I see in Dimitar's code that the RevitFaceReferences are added "manually" to the tags of the DS geometry. I will definitely impliment this in my face selection methods. Will let you know when it's done. 
Cheers!

**Comment by MostafaElAyoubi** [comment]
@brunotux Ok it's done :) 
![image](https://user-images.githubusercontent.com/20224923/27677894-8e2dffdc-5cb3-11e7-9ef9-68771cbb5502.png)

I went ahead and did the same for my edge selection method, which makes it better than the OOTB node 😄 
![image](https://user-images.githubusercontent.com/20224923/27678360-40e4aa30-5cb5-11e7-911e-a8ee1d244632.png)

It's all in version 2017.06.29 of the package!
