### ISSUE TITLE
Select faces only returns multiples of one face

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#26]
Hi Mostafa,
In version 2017.7.5 when using UI.SelectFaces, the form only returns as many instances of the same surface as there were faces in the selection (probably multiple instances of the first face of the selection):
![grafik](https://user-images.githubusercontent.com/3014437/29924270-c12c57b4-8e5c-11e7-8e71-47ca92e09eee.png)

**Comment by MostafaElAyoubi** [comment]
Hi Andreas,
thanks for pointing this out. It was actually pretty fast to fix, just a mistake in code when trying to flatten the list of surfaces. 
I'll update the package this afternoon .

**Comment by MostafaElAyoubi** [comment]
Alright it's done :)
