### ISSUE TITLE
Issue with text wrapping in InputGroups

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#28]
Hi Mostafa,
I found another small issue with InputGroups: the text wrapping of text notes is slightly off:
![grafik](https://user-images.githubusercontent.com/3014437/30630422-e278727a-9de0-11e7-903c-ec878f75016b.png)

**Comment by MostafaElAyoubi** [comment]
Hi Andreas,
thanks for letting me know! :) 
I fixed that (version 2017.9.2 of the package)
![image](https://user-images.githubusercontent.com/20224923/30636868-f25da1e0-9df6-11e7-9a38-e9e62fd428b0.png)

**Comment by andydandy74** [comment]
Wow, that was fast. Thanks!
