### ISSUE TITLE
Can't group radio buttons

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#29]
Hi Mostafa,
I get an error when trying to put radio buttons into a group:
![grafik](https://user-images.githubusercontent.com/3014437/32783828-5c777232-c94d-11e7-9f57-ede7c2af2323.png)

**Comment by MostafaElAyoubi** [comment]
Hi Andreas, 
actually this has more to do with the fact that inputgroups need a list of inputs. Something like this will work if you only need one input in the group: 

![image](https://user-images.githubusercontent.com/20224923/33166506-ce614e9c-d03a-11e7-8cc0-a527b28da50b.png)

**Comment by andydandy74** [comment]
:-D Haha, I just assumed that it would work the same way as the "inputs" input of the form node. Thanks.
