### ISSUE TITLE
Boolean inputs in InputGroups break right-hand border

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#31]
This is just a minor thing, but I noticed that Boolean inputs cause the right-hand border of InputGroups to break:
![grafik](https://user-images.githubusercontent.com/3014437/32784917-6f791a2c-c950-11e7-9279-bdade4850d0c.png)

**Comment by MostafaElAyoubi** [comment]
Thanks for letting me know! I fixed it. It'll be published today. 
![image](https://user-images.githubusercontent.com/20224923/33165972-e8928094-d038-11e7-90c1-3401a36d3b16.png)

**Comment by MostafaElAyoubi** [comment]
This issue is fixed in version 2017.11.23 of the package
