### ISSUE TITLE
ListView element count protrudes into list when no inputname is given

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#32]
Another thing I stumbled upon today: If I activate the element count in a ListView, but leave the InputName blank I get this:
![grafik](https://user-images.githubusercontent.com/3014437/32785643-540091ce-c952-11e7-9f98-16c3d6e19388.png)
Perhaps it would make more sense to relocate the element count next to "Select all / none"?

**Comment by MostafaElAyoubi** [comment]
Thanks for pointing it out! Fixed it 
![image](https://user-images.githubusercontent.com/20224923/33169529-50725016-d045-11e7-9d83-ca729928887b.png)
It'll be published today aswell

**Comment by MostafaElAyoubi** [comment]
This issue is fixed in version 2017.11.23 of the package
