### ISSUE TITLE
Listview default value indices shifted

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#35]
Hi @MostafaElAyoubi,
in Data-Shapes 2018.5.6 the default value indices are shifted by 1.
This can lead to the form not displaying in cases where the last item in the list is included in the list of default value indices.
I would have created a pull request, but it seems this repository is not up to date with what is available on the package manager. The issue is caused in line 525 of UI.MultiInputForm++:
```
				for i in j.default_values:
					defInd = lvItems.index([x for x in j.keys() if not (x == 'inputname' or x == 'height' or x == 'highlight' or x == 'display_mode' or x == 'element_count' or x == 'default_values' or x == 'sorted' or i == 'showId')][i])
					lv.Items[defInd].Checked = True
````
Just replace ```i == 'showId'``` with ```x == 'showId'```.

**Comment by MostafaElAyoubi** [comment]
Okay issue fixed and github repository updated

**Comment by andydandy74** [comment]
Thanks!
