### ISSUE TITLE
MultipleInputForm++ won't take ConditionalInput Data

### ISSUE THREAD

**Issue by david-pbk** [MostafaElAyoubi/Data-shapes#45]
Trying out Conditional Input and got error:
NameError: global name 'Ratio' is not defined

Line 1367 currently reads:
					addinput(condition_pannel,d,25 * yRatio,xinput-25 * xRatio,80 * Ratio,90 * xRatio,importcolorselection)

I believe it's missing an x:
					addinput(condition_pannel,d,25 * yRatio,xinput-25 * xRatio,80 * xRatio,90 * xRatio,importcolorselection)

Made the edit in my graph and it's worked so far.

**Comment by MostafaElAyoubi** [comment]
Hi @david-pbk , thanks for reporting. 
Could you please provide more context? Revit and Dynamo versions, maybe also a screenshot? That would help better understand the issue.

**Comment by david-pbk** [comment]
I've been upgrading my graphs and this one's been fixed :-)
![image](https://user-images.githubusercontent.com/47759899/124846234-3afbfa00-df4d-11eb-8f9c-85ba3f0a8b9c.png)
Awesome-O
