### ISSUE TITLE
Wish: Variable input label width

### ISSUE THREAD

**Issue by schnesv1** [MostafaElAyoubi/Data-shapes#46]
Hi Mostafa,
I think it would be useful to be able to change the width of the inputs labels in some cases. These labels seem to have a fixed width of 120 pixels which doesn't change when the window width is increased. This can be very narrow when working on a system which uses the windows scaling option. In these cases, a form can get unusable because it's stretched beyond the display height. I attached a picture of your Modification Tracker as an example.

![grafik](https://user-images.githubusercontent.com/43970416/63245479-9725da00-c260-11e9-92b8-6ba9b589a751.png)

It's only a minor issue because it can be avoided by using a TextNode.

**Comment by MostafaElAyoubi** [comment]
Hey @schnesv1, thanks for your comment.
I agree with you. Plus it wouldn't be complicated at all to implement. This will be taken into account in the next version of the package.

**Comment by MostafaElAyoubi** [comment]
This was implemented in version 2021.2.92 of the package.
