### ISSUE TITLE
BUG - Select model elements

### ISSUE THREAD

**Issue by jmcouffin** [MostafaElAyoubi/Data-shapes#51]
Hello Mostafa, 
the select model elements data node from the UI section does not seem to work in Revit 2021 and 2020 but the select model elements data ordered does.

Take a look at the video

[bugDS.zip](https://github.com/MostafaElAyoubi/Data-shapes/files/4662388/bugDS.zip)

**Comment by MostafaElAyoubi** [comment]
hi @jmcouffin ,
thanks for reporting. Not sure what was causing this in the version of the package you were using but upgrading to the latest version should do the job. Here's with version  2020.2.6 of the package:
![selectModelElements](https://user-images.githubusercontent.com/20224923/82736136-8fcbb980-9d27-11ea-9327-9537c72f78df.gif)

Please let me know how it goes!

**Comment by jmcouffin** [comment]
Cool, Thanks @MostafaElAyoubi
