### ISSUE TITLE
SelectFaces from a FamilyInstance needs a transformed geometry

### ISSUE THREAD

**Issue by denizmaral** [MostafaElAyoubi/Data-shapes#71]
If you select faces from a FamilyInstance, they are going to place wrongly. In this case the geometry should get totally transformed:

![grafik](https://user-images.githubusercontent.com/55183821/155715616-41080b22-8e9e-4d30-88c2-ae30369d39eb.png)

Here you can find some scenarios:

![grafik](https://user-images.githubusercontent.com/55183821/155714800-beac3404-6ee9-4ad6-b0eb-b434c11c1ccf.png)

If you edit the file like that it works:
![grafik](https://user-images.githubusercontent.com/55183821/155714871-6fdb0663-fab7-493f-8d36-d88105fb83ab.png)

**Comment by MostafaElAyoubi** [comment]
implemented in the package
