### ISSUE TITLE
UI.MultipleInputForm++ throws error if package in non-standard location

### ISSUE THREAD

**Issue by andydandy74** [MostafaElAyoubi/Data-shapes#8]
When running the most recent version of UI.MultipleInputForm++ without providing a path to a custom logo, I get the following error in line 581: ```IOError: [Errno 2] C:\Users\{MY_USERNAME}\AppData\Roaming\Dynamo\Dynamo Revit\1.2\packages\Data-Shapes\extra\a.png```
The cause for this is that I don't have the package installed in that location.

**Comment by MostafaElAyoubi** [comment]
Thanks for pointing it out. There used to be a "try -  except" on that part but I took it off while I was working on it. I forgot to add it back before publishing the package.
